--- #YAML:1.0
name:                Muldis-D
version:             0.79.0
abstract:            Formal spec of Muldis D relational DBMS lang
license:             gpl
author:              
    - Darren Duncan <perl@DarrenDuncan.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    version:                       0.74
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
